### ISSUE TITLE
Send backpresses to the image viewer only

### ISSUE THREAD

**Issue by Gloix** [aeharding/wefwef#111]
Backpresses are not handled correctly:

- Open app in posts section
- Open a post with an image
- Tap on the image to view full screen
- Press back

Actual: UI below the image performs a back transition and then the image viewer is dismissed.
Expected: Only image viewer is dismissed. Post should be still open.

**Comment by aeharding** [comment]
Hello! Thanks for the issue.

I suppose we could push a query param, ?imageViewer=1 or something to the url. That would allow android back button to work.

**Comment by aperson** [comment]
This also seems to happen when replying to a post.  You can open up the comment screen and use the back button.  If you exit the comment screen, you will find yourself back one screen from where you were.

**Comment by ToNIX-** [comment]
> 

I just tested on wefwef 0.12.0 and yeah, you get a prompt asking you if you want to discard your comment now (great!), but it doesn't go back to the thread, it goes back directly to the posts list.

As for images, it also goes back instead of simply closing the image.

I made a screen record of the issue.

https://github.com/aeharding/wefwef/assets/9488095/7784098d-90a4-4a46-8f28-a2d4140fa3ef

**Comment by rsammelson** [comment]
I think #93 is the same thing but the example is for a different menu.

**Comment by beeb** [comment]
Hijacking this issue related to closing the image viewer to say that a tap in the overlay around the image should close the preview too! Thanks in advance :)

**Comment by aeharding** [comment]
I'm working on this now.

@beeb Please make a different issue for tap backdrop if it doesn't exist :)

**Comment by beeb** [comment]
This can be closed right?

**Comment by Gloix** [comment]
Thanks for fixing this. Love the app!
