### ISSUE TITLE
Firefox Android is not using the apple-touch-icon icon.

### ISSUE THREAD

**Issue by nathanielcwm** [aeharding/wefwef#120]
Tested with Firefox 115.0b9

When installing wefwef as an app using Firefox it isn't taking the apple-touch-icon icon or favicon and is instead only using a w for the icon.

I've seen some old bug reports that state that a 180x180px icon is sometimes required for it to choose to use it, but I'm not sure how true that is.

**Comment by aeharding** [comment]
Yeah, I can confirm. This is super annoying.

**Comment by nathanielcwm** [comment]
I think I might want to take a shot at fixing this. @aeharding how did you make the logo? As there seems to be quite a lot of JPEG artifacts.

**Comment by nathanielcwm** [comment]
Relevant documentation:
[Apple](https://developer.apple.com/design/human-interface-guidelines/app-icons)
[Webhint](https://webhint.io/docs/user-guide/hints/hint-apple-touch-icons/)
[MDN](https://developer.mozilla.org/en-US/docs/Web/Manifest)

**Comment by aeharding** [comment]
tbh I made this in approximately 30 seconds with Apple Preview. 😂

I would be happy to replace it completely with something that looks practically the same (so it's not a controversial change), if you (or any other wefwef users) know their way around illustrator.

I have some comments too on formats that would be needed over here, such as a maskable variant:

https://github.com/aeharding/wefwef/pull/71#issuecomment-1613856503

(I am holding off on merging that PR because it's an artistic change vs a technical one.)

**Comment by nathanielcwm** [comment]
Could I have a link to the background? It looks really familiar but I can't quite place my finger on where it's from.

**Comment by aeharding** [comment]
Honestly, I don't remember, sorry.

**Comment by nathanielcwm** [comment]
![test](https://github.com/aeharding/wefwef/assets/22572406/f50346fa-fe4a-4bc4-afd1-1cb59482c395)

Does something like this look fine?

**Comment by nathanielcwm** [comment]
Weird: on wefwef.app the issue persists but it's fine on opnxng.com and my local instance when I was testing.
