### ISSUE TITLE
nginx container not deploying while self hosting

### ISSUE THREAD

**Issue by driftywinds** [aeharding/wefwef#24]
it just gets stuck on "container nginx starting"

**Comment by aeharding** [comment]
Hi there! The docker-compose is used for setting up https on https://wefwef.app. It's not needed to run wefwef. It's probably failing because you don't have private keys available for nginx to grab onto. I'll remove this file shortly so it doesn't confuse people.

I recommend just using the base Docker image for wefwef, which should work just fine. Deploying with https will depend on your unique setup. If you still need to setup letsencrypt in docker, you can follow a guide like this:

https://www.digitalocean.com/community/tutorials/how-to-secure-a-containerized-node-js-application-with-nginx-let-s-encrypt-and-docker-compose

**Comment by driftywinds** [comment]
> Hi there! The docker-compose is used for setting up https on https://wefwef.app. It's not needed to run wefwef. It's probably failing because you don't have private keys available for nginx to grab onto. I'll remove this file shortly so it doesn't confuse people.
> 
> I recommend just using the base Docker image for wefwef, which should work just fine. Deploying with https will depend on your unique setup. If you still need to setup letsencrypt in docker, you can follow a guide like this:
> 
> https://www.digitalocean.com/community/tutorials/how-to-secure-a-containerized-node-js-application-with-nginx-let-s-encrypt-and-docker-compose

Even after the wefwef container has been deployed I can't access it on localhost on the port mentioned on docker, (5314 i believe). Are there docs that point to where I acn access wefwef that has been deployed?

**Comment by aeharding** [comment]
Can you try:

```
docker build -t wefwef .
docker run --rm -it -p 5314:5314 wefwef
```

That should work on port http://localhost:5314.

**Comment by driftywinds** [comment]
> docker run --rm -it -p 5314:5314 wefwef

This worked! Thank alot!
