### ISSUE TITLE
Switch to pnpm

### ISSUE THREAD

**Issue by aeharding** [aeharding/wefwef#258]
Builds are taking foreverrrrr

Let's switch to pnpm!

**Comment by mdecourcy** [comment]
I can take a look at this after work tomorrow (~5pm pst) if no one gets to it before

**Comment by jonesetc** [comment]
Just gave a quick spin to see what this is like and running the dev server and a build seems to work fine as a drop in with a small amount of config added that lets wefwef continue to access transitive dependencies (done a good bit in the markdown code) instead of adding all of those as direct dependencies (I believe it was around 8 that would need to be added).

.npmrc
```
shamefully-hoist=true
strict-peer-dependencies=false
```

What is not working is `pnpm test`. This is getting stuck on the vite pwa virtual import and I'm afraid that I can't tell why

```
 FAIL  src/App.test.tsx [ src/App.test.tsx ]
Error: Cannot find module '/@vite-plugin-pwa/virtual:pwa-register/react' imported from '~/code/wefwef/src/pages/settings/update/UpdateContext.tsx'.

- If you rely on tsconfig.json to resolve modules, please install "vite-tsconfig-paths" plugin to handle module resolution.
 - Make sure you don't have relative aliases in your Vitest config. Use absolute paths instead. Read more: https://vitest.dev/guide/common-errors
```

I went down a few debugging paths and tried adding to both `tsconfig.json` `types` and `include` sections but no dice.

Not going to bang my head against this wall as i'm new to vite and not sure i understand the resolution inner workings enough to be helpful. But hopefully that will help whoever else wants to take it for a spin.

**Comment by FitzHawke** [comment]
I took a swing at this too, but ran into the same testing errors as @jonesetc. I'm going to dig a bit and see what I can figure out, but if anyone happens by here and has an idea help would be appreciated!

Going to open a draft pr with progress so far.
