### ISSUE TITLE
Searching for communities from another instance doesn't work

### ISSUE THREAD

**Issue by IverCoder** [aeharding/wefwef#276]
The `@` part gets turned to `%40`. Example, `!technology@beehaw.org` would become `!technology%40beehaw.org`.

![Screenshot_20230705_131849_Kiwi Browser](https://github.com/aeharding/wefwef/assets/92661164/e210175f-4195-439e-8e07-7047e93c30df)
![Screenshot_20230705_131855_Kiwi Browser](https://github.com/aeharding/wefwef/assets/92661164/513c2b92-1f45-4567-b625-cde656b269d1)

**Comment by mufeedali** [comment]
Can reproduce

**Comment by mdecourcy** [comment]
Related: #265

**Comment by bdonvr** [comment]
> Related: #265

Sort of- the fix for this isn't as easy. Lemmy expects an "@" when going to a user page, not a URI encoding. But when searching for a community it DOES expect a URI encoded string. Test this by searching on the lemmy site. WefWef sends the correct request. I tried just sending the string unchanged, but it doesn't solve the issue. There's more to this one.

![IMG_1187](https://github.com/aeharding/wefwef/assets/10774527/0ec2e50b-4fbc-4f36-9cbd-89698e9cc8cf)

**Comment by IverCoder** [comment]
Still occuring after upgrading to `0.14.0`.

**Comment by bdonvr** [comment]
> Still occuring after upgrading to `0.14.0`.

Should be fixed by https://github.com/aeharding/wefwef/pull/277

Which is likely next release

**Comment by IverCoder** [comment]
Finally works. Thank you for the swift response!
![Screenshot_20230706_171445_Kiwi Browser](https://github.com/aeharding/wefwef/assets/92661164/9d372288-b962-4afe-b29d-7b98c707fe66)
