### ISSUE TITLE
Gallery closes on auto screen rotate

### ISSUE THREAD

**Issue by tranzystorek-io** [aeharding/wefwef#304]
When turning screen on Android in gallery mode, instead of rotating the image the gallery component instead closes and wefwef displays auto-rotated feed

Update: this happens only when rotating from vertical to horizontal, not the other way around.

**Comment by aeharding** [comment]
This is due to virtuoso remounting grid items on rotation.

That causes photoswipe to close.

It looks like to solve this we're going to need to move photoswipe outside of the infinite grid. We may also need to use photoswipe directly instead of react-photoswipe.

Luckily infinite scroll case is specifically accounted for in photoswipe library :) https://photoswipe.com/data-sources#separate-dom-and-data

Assigning myself
